apiVersion: v1
kind: Secret
metadata:
  name: blog-neo4j
  namespace: demo
  labels:
    app: blog-neo4j
type: Opaque
data:
  neo4j-password: MTcxOGJhYTIxNGY2MjUxYzRmMWU3MDBhMjVhZmE3NGE5MWYxM2M2MTVhYzFhYmEwOWViMWQ5ZjQ3OWQy
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blog-neo4j
  namespace: demo
spec:
  serviceName: blog-neo4j
  replicas: 1
  selector:
    matchLabels:
      app: blog-neo4j
  template:
    metadata:
      labels:
        app: blog-neo4j
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: neo4j
          image: neo4j:4.4.4
          env:
            - name: NEO4J_AUTH
              value: "none"
          ports:
            - containerPort: 7474
            - containerPort: 7687
          volumeMounts:
            - name: data
              mountPath: /var/lib/neo4j/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: blog-neo4j
  namespace: demo
spec:
  selector:
    app: blog-neo4j
  ports:
    - name: web
      port: 7474
    - name: bolt
      port: 7687
