apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: <your-docker-repository-name>/gateway
      context: ../gateway
      jib: {}
    - image: <your-docker-repository-name>/blog
      context: ../blog
      jib: {}
    - image: <your-docker-repository-name>/store
      context: ../store
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
